### ISSUE TITLE
Start location cannot be removed

### ISSUE THREAD

**Issue by xivk** [oSoc18/bike4brussels#13]
Start location cannot be removed from the map once set, the only way to change it is via geocoding. 

Suggested fix: 
- Remove the marker when the 'From' field is emptied but leave the destination.
- When clicking on the map, set the start location when the destination is already there.
- Geocoding works as it does now.

**Comment by Fizz55** [comment]
adf20bf3c9e942db1c64627d7027fc07038344e4
e3341402676d454a984f9f5ab4d324f5edd60f02
b3fb3c8267a186f2d6c2f9317e9cdba4586cf323
