### ISSUE TITLE
Make sure domain redirects later

### ISSUE THREAD

**Issue by xivk** [oSoc18/bike4brussels#2]
We are currently using `bike4brussels.osm.be`, make sure this redirects later to whatever the client wants to use.

**Comment by jbelien** [comment]
Brussels Mobility agreed to make https://routeplanner.bike.brussels/ to 2018 version (and kill 2017 version 💀)

**Comment by Fizz55** [comment]
That's awesome news!

**Comment by jbelien** [comment]
You just have to change the URL in [constants.js](https://github.com/oSoc18/bike4brussels/blob/master/js/constants.js#L6)
