### ISSUE TITLE
Sharing a link doesn't work

### ISSUE THREAD

**Issue by xivk** [oSoc18/bike4brussels#5]
Sharing a link doesn't work right now. I tried to copy this link:

https://bike4brussels.osm.be/?loc1=4.2914543220405506,50.861193528273105&loc2=4.332748551061144,50.85170872208812&

But no route shows up. 

Tested on lastest firefox.

**Comment by Fizz55** [comment]
Opening this link does show routes for me now (in Chrome). Is this a firefox related issue? Could you test again if the issue remains please? There were some deployment issues that day..

**Comment by xivk** [comment]
This is fixed/false positive.
