### ISSUE TITLE
Mobile: Ask to add app to home screen after 3 uses

### ISSUE THREAD

**Issue by r0b93y** [oSoc18/bike4brussels#8]

**Comment by Fizz55** [comment]
af9013d7119bc56604251acf90fb2df144d99b8e
e27496d15ba283c91d27c6b21cbb3e4f3ef9211f
3d4422a82c353c0d3c70ced6152bdfcbbd5342d3
798a42f10645fb369f08f517bcb16ef890116097
48d3d1a6414010a158bdb7934103da25b6eb66bc
f00cc17692c197f09442b548a7d7b6fc60ec3b83
9cc0c99006f83c9f7ee76ad4fb7c8a88e4203340
